# Generated by Django 3.2.9 on 2021-12-02 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_auto_20211202_0211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
