# Generated by Django 3.2.9 on 2021-12-02 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_reservation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('event', 'service', 'subservice', 'product')},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
    ]
